# demo config application.yml and application.properties

# spring config
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: messages

  #config r2dbc
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/auth
    username: admin
    password: admin
  codec:
    max-in-memory-size: 100MB

  #config oauth2 with keycloak
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: http://localhost:8080/realms/ezbuy-server/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ezbuy-client
            client-secret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ezbuy-server/protocol/openid-connect/certs
      keycloak:
        client-id: ezbuy-client

#cache2l config
cache2l:
  reflectionPath: io.hoangtien2k3.commons
  enable-global-cache: true
  redis:
    externalMode: true
    externalCluster: 10.207.59.4:8001,10.207.59.4:8002,10.207.60.5:8003,10.207.60.6:8004
    username: redis
    password: redis@2024

## unauthenticated endpoints config
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /v1/demo/post
      methods:
        - POST
    - uri: /v1/demo/put
      methods:
        - PUT
    - uri: /v1/demo/delete
      methods:
        - DELETE
    - uri: /v1/demo/head
      methods:
        - HEAD
    - uri: /v1/demo/options
      methods:
        - OPTIONS

# web client config
#client:
#  keycloak:
#    address: http://localhost:8080/realms/ezbuy-server/protocol/openid-connect
#    name: keycloak
#    auth:
#      client-id: ezbuy-client
#      client-secret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw

# minio server config
#minio:
#  bucket: ezbuy-bucket
#  enabled: true
#  baseUrl: http://localhost:9000
#  publicUrl: http://localhost:9000/ezbuy-bucket
#  accessKey: 4DoaZ0KdzpXdDlVK104t
#  secretKey: nuRiQUIJNVygMOHhmtR4LT1etAa7F8PQOsRGP5oj
#  private:
#    bucket: ezbuy-private

#generate public key
#hashing-password:
#  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw5e+CZbXbC8SRbrp+X9O4QRrKQWRu2zJpYGmGtP3bdS6NtsVBaJz2hHwF1KeEzZTnlW/jy7NOYYR5Rp5nD1RfAJooxZxgO7BcZZKbsnBNe+KLUQrxNOgkx2ZpMs60UdzToz0IvIN5L5NFaiKq5/WwRpG4aIM8iV/ME1L/QQw0FDD7m/2PUxDlANXJl5hZgXfZ1hpo/31HXkBofJTWJ/MdTAnxR4u5y+mXYUsf9GmCmA5exPpPZZv1qT1D7AWv0CXi5Ftd2ylbD6jAtF5MC1ngO4FEGZh9uTwXQh2x8FJmc2U7KKTQMWuhbXtkANVVLMg+GPx7lTxDTwQpKmldf5UDuuzcBQIDAQAB

#proxy-client:
#  host: 10.207.156.52
#  port: 3128
