#name: Documentation
#
#on:
#  push:
#    branches:
#      - main
#
#permissions:
#  contents: write
#
#jobs:
#  cancel-previous-workflows:
#    if: github.actor!= 'dependabot-preview[bot]'
#    env:
#      github_token: ${{ secrets.GITHUB_TOKEN }}
#    name: Cancel previous workflow runs
#    runs-on: ubuntu-latest
#    steps:
#      - uses: styfle/cancel-workflow-action@0.9.1
#        with:
#          access_token: ${{ github.token }}
#
#  deploy:
#    runs-on: ubuntu-latest
#    timeout-minutes: 60
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '21'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Generate Javadoc
#        run: mvn javadoc:javadoc
#
#      - name: Deploy Documentations
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: target/site/apidocs
